name: CI

on:
  push:
    paths-ignore:
      - 'example/**'
      - '*.md'
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'example/**'
      - '*.md'
    branches:
      - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: |
        npm install
        npm install -g c8

    - name: Test w/ Coverage
      run: c8 --include=src npm test

    # - name: Report
    #   if: matrix.nodejs >= 14
    #   run: |
    #     c8 report --reporter=text-lcov > coverage.lcov
    #     bash <(curl -s https://codecov.io/bash)
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
